### ISSUE TITLE
1.0.1 - Syntax Error

### ISSUE THREAD

**Issue by lubbertkramer** [lubbertkramer/nl.infinityideas.amberalert#2]
Crash report: 
    SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/app.js:42:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by lubbertkramer** [comment]
Fixed in 1.0.5
