### ISSUE TITLE
1.0.6 - Unexpected end of input

### ISSUE THREAD

**Issue by satbopper** [lubbertkramer/nl.infinityideas.amberalert#5]
Stack trace:

SyntaxError: Unexpected end of input
at Object.parse (native)
at IncomingMessage.<anonymous> (/app.js:44:14)
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:923:12)
at nextTickCallbackWith2Args (node.js:458:9)
at process._tickCallback (node.js:372:17)

Exit code: 1
Exit signal: null

**Comment by lubbertkramer** [comment]
Busy with 1.1 where i change the method of request for the Amber Alert. Preparing to do it by location. If you want you can try/test 1.0.7 (install by CLI)

**Comment by lubbertkramer** [comment]
Added some more changes, will push 1.0.8 to Athom if will stay stable for two days

**Comment by lubbertkramer** [comment]
Solved in 1.0.8
