### ISSUE TITLE
App Chrashed

### ISSUE THREAD

**Issue by hvhol** [lubbertkramer/nl.infinityideas.amberalert#6]
Stack trace:

SyntaxError: Unexpected token <
at Object.parse (native)
at IncomingMessage.<anonymous> (/app.js:44:14)
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:921:12)
at nextTickCallbackWith2Args (node.js:442:9)
at process._tickCallback (node.js:356:17)

Exit code: 1
Exit signal: null

**Comment by lubbertkramer** [comment]
Thanks, same as issue https://github.com/lubbertkramer/nl.infinityideas.amberalert/issues/5. You could try to install 1.0.7 by CLI, i'm running it now for testing
